[2016-04-14 21:01:43,298: INFO/MainProcess] Received task: tasks.add[b1722d01-7547-495c-89f8-cd62b128ea09]
[2016-04-14 21:01:43,299: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10b206d70> (args:('tasks.add', 'b1722d01-7547-495c-89f8-cd62b128ea09', (2, 4), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': (2, 4), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u'celery'}, 'expires': None, u'hostname': 'celery@Jhons-MacBook-Pro.local', 'task': 'tasks.add', 'callbacks': None, u'correlation_id': u'b1722d01-7547-495c-89f8-cd62b128ea09', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'505f4f70-581f-3e6d-85bd-decf6578c9f1', 'id': 'b1722d01-7547-495c-89f8-cd62b128ea09', u'headers': {}}) kwargs:{})
[2016-04-14 21:01:43,300: DEBUG/MainProcess] Task accepted: tasks.add[b1722d01-7547-495c-89f8-cd62b128ea09] pid:10197
[2016-04-14 21:01:43,300: WARNING/Worker-2] 6
[2016-04-14 21:01:43,301: INFO/MainProcess] Received task: tasks.mul[bd985b53-02da-421a-80fc-88ad881aed97]
[2016-04-14 21:01:43,301: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10b206d70> (args:('tasks.mul', 'bd985b53-02da-421a-80fc-88ad881aed97', (2, 1), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': (2, 1), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u'celery'}, 'expires': None, u'hostname': 'celery@Jhons-MacBook-Pro.local', 'task': 'tasks.mul', 'callbacks': None, u'correlation_id': u'bd985b53-02da-421a-80fc-88ad881aed97', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'505f4f70-581f-3e6d-85bd-decf6578c9f1', 'id': 'bd985b53-02da-421a-80fc-88ad881aed97', u'headers': {}}) kwargs:{})
[2016-04-14 21:01:43,302: INFO/MainProcess] Task tasks.add[b1722d01-7547-495c-89f8-cd62b128ea09] succeeded in 0.00215362000745s: None
[2016-04-14 21:01:43,303: DEBUG/MainProcess] Task accepted: tasks.mul[bd985b53-02da-421a-80fc-88ad881aed97] pid:10198
[2016-04-14 21:01:43,303: WARNING/Worker-3] 2
[2016-04-14 21:01:43,304: INFO/MainProcess] Received task: tasks.mul[2293c46d-712f-4d37-a56c-502b8f928914]
[2016-04-14 21:01:43,304: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10b206d70> (args:('tasks.mul', '2293c46d-712f-4d37-a56c-502b8f928914', (2, 0), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': (2, 0), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u'celery'}, 'expires': None, u'hostname': 'celery@Jhons-MacBook-Pro.local', 'task': 'tasks.mul', 'callbacks': None, u'correlation_id': u'2293c46d-712f-4d37-a56c-502b8f928914', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'505f4f70-581f-3e6d-85bd-decf6578c9f1', 'id': '2293c46d-712f-4d37-a56c-502b8f928914', u'headers': {}}) kwargs:{})
[2016-04-14 21:01:43,304: INFO/MainProcess] Task tasks.mul[bd985b53-02da-421a-80fc-88ad881aed97] succeeded in 0.00210854993202s: None
[2016-04-14 21:01:43,305: DEBUG/MainProcess] Task accepted: tasks.mul[2293c46d-712f-4d37-a56c-502b8f928914] pid:10203
[2016-04-14 21:01:43,307: INFO/MainProcess] Received task: tasks.xsum[1a3b2960-de8f-4c5c-a488-5a0ea36346d6]
[2016-04-14 21:01:43,307: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10b206d70> (args:('tasks.xsum', '1a3b2960-de8f-4c5c-a488-5a0ea36346d6', (2,), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': (2,), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u'celery'}, 'expires': None, u'hostname': 'celery@Jhons-MacBook-Pro.local', 'task': 'tasks.xsum', 'callbacks': None, u'correlation_id': u'1a3b2960-de8f-4c5c-a488-5a0ea36346d6', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'505f4f70-581f-3e6d-85bd-decf6578c9f1', 'id': '1a3b2960-de8f-4c5c-a488-5a0ea36346d6', u'headers': {}}) kwargs:{})
[2016-04-14 21:01:43,308: ERROR/MainProcess] Task tasks.mul[2293c46d-712f-4d37-a56c-502b8f928914] raised unexpected: ZeroDivisionError('integer division or modulo by zero',)
Traceback (most recent call last):
  File "/Users/jhonjairoscalablepath/PycharmProjects/celery_error_handling_venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/jhonjairoscalablepath/PycharmProjects/celery_error_handling_venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/jhonjairoscalablepath/Dropbox/PycharmProjects/celery_error_handling/proj/tasks.py", line 15, in print_div
    print x/y
ZeroDivisionError: integer division or modulo by zero
[2016-04-14 21:01:43,308: WARNING/Worker-7] 0.69314718056
[2016-04-14 21:01:43,309: DEBUG/MainProcess] Task accepted: tasks.xsum[1a3b2960-de8f-4c5c-a488-5a0ea36346d6] pid:10202
[2016-04-14 21:01:43,309: INFO/MainProcess] Task tasks.xsum[1a3b2960-de8f-4c5c-a488-5a0ea36346d6] succeeded in 0.00173902302049s: None
[2016-04-14 21:01:43,310: INFO/MainProcess] Received task: tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a]
[2016-04-14 21:01:43,310: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10b206d70> (args:('tasks.xsum', 'a4090917-76d4-4814-b8b6-4298e82f275a', (-1,), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': (-1,), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u'celery'}, 'expires': None, u'hostname': 'celery@Jhons-MacBook-Pro.local', 'task': 'tasks.xsum', 'callbacks': None, u'correlation_id': u'a4090917-76d4-4814-b8b6-4298e82f275a', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'505f4f70-581f-3e6d-85bd-decf6578c9f1', 'id': 'a4090917-76d4-4814-b8b6-4298e82f275a', u'headers': {}}) kwargs:{})
[2016-04-14 21:01:43,311: DEBUG/MainProcess] Task accepted: tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a] pid:10199
[2016-04-14 21:01:43,312: ERROR/Worker-4] tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a]: A task execution failed
[2016-04-14 21:01:43,313: ERROR/Worker-4] tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a]: task exception math domain error
[2016-04-14 21:01:43,313: ERROR/Worker-4] tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a]: task_id a4090917-76d4-4814-b8b6-4298e82f275a
[2016-04-14 21:01:43,313: ERROR/Worker-4] tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a]: task args (-1,)
[2016-04-14 21:01:43,313: ERROR/Worker-4] tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a]: task kwargs {}
[2016-04-14 21:01:43,313: ERROR/Worker-4] tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a]: task error_info Traceback (most recent call last):
  File "/Users/jhonjairoscalablepath/PycharmProjects/celery_error_handling_venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/jhonjairoscalablepath/PycharmProjects/celery_error_handling_venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/jhonjairoscalablepath/Dropbox/PycharmProjects/celery_error_handling/proj/tasks.py", line 20, in print_log
    print log(x)
ValueError: math domain error

[2016-04-14 21:01:43,314: ERROR/MainProcess] Task tasks.xsum[a4090917-76d4-4814-b8b6-4298e82f275a] raised unexpected: ValueError('math domain error',)
Traceback (most recent call last):
  File "/Users/jhonjairoscalablepath/PycharmProjects/celery_error_handling_venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/jhonjairoscalablepath/PycharmProjects/celery_error_handling_venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/jhonjairoscalablepath/Dropbox/PycharmProjects/celery_error_handling/proj/tasks.py", line 20, in print_log
    print log(x)
ValueError: math domain error
[2016-04-14 21:20:37,252: DEBUG/MainProcess] | Worker: Closing Hub...
[2016-04-14 21:20:37,254: DEBUG/MainProcess] | Worker: Closing Pool...
[2016-04-14 21:20:37,255: DEBUG/MainProcess] | Worker: Closing Consumer...
[2016-04-14 21:20:37,255: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2016-04-14 21:20:37,256: DEBUG/MainProcess] | Consumer: Closing Connection...
[2016-04-14 21:20:37,256: DEBUG/MainProcess] | Consumer: Closing Events...
[2016-04-14 21:20:37,256: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2016-04-14 21:20:37,257: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2016-04-14 21:20:37,257: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2016-04-14 21:20:37,257: DEBUG/MainProcess] | Consumer: Closing Control...
[2016-04-14 21:20:37,257: DEBUG/MainProcess] | Consumer: Closing Heart...
[2016-04-14 21:20:37,257: DEBUG/MainProcess] | Consumer: Closing event loop...
[2016-04-14 21:20:37,257: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2016-04-14 21:20:37,257: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2016-04-14 21:20:37,258: DEBUG/MainProcess] | Consumer: Stopping Control...
[2016-04-14 21:20:37,263: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2016-04-14 21:20:37,264: DEBUG/MainProcess] Canceling task consumer...
[2016-04-14 21:20:37,264: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2016-04-14 21:20:37,266: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2016-04-14 21:20:37,266: DEBUG/MainProcess] | Consumer: Stopping Events...
[2016-04-14 21:20:37,266: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2016-04-14 21:20:37,266: DEBUG/MainProcess] | Worker: Stopping Pool...
[2016-04-14 21:20:38,314: DEBUG/MainProcess] | Worker: Stopping Hub...
[2016-04-14 21:20:38,316: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2016-04-14 21:20:38,316: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2016-04-14 21:20:38,316: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2016-04-14 21:20:38,316: DEBUG/MainProcess] Canceling task consumer...
[2016-04-14 21:20:38,317: DEBUG/MainProcess] Closing consumer channel...
[2016-04-14 21:20:38,317: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2016-04-14 21:20:38,317: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2016-04-14 21:20:38,317: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2016-04-14 21:20:38,321: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
